//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class DataReaderWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(DataReader), typeof(System.Object));
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}
}

