//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class LuaPlayInterfaceWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(LuaPlayInterface), typeof(PlayBase));
		L.RegFunction("Awake", Awake);
		L.RegFunction("GetPlayID", GetPlayID);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Awake(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			LuaPlayInterface obj = (LuaPlayInterface)ToLua.CheckObject<LuaPlayInterface>(L, 1);
			obj.Awake();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetPlayID(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			LuaPlayInterface obj = (LuaPlayInterface)ToLua.CheckObject<LuaPlayInterface>(L, 1);
			int o = obj.GetPlayID();
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

