//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class PlayDataConfigWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(PlayDataConfig), typeof(DataReader));
		L.RegFunction("LoadConfig", LoadConfig);
		L.RegFunction("GetDataByID", GetDataByID);
		L.RegFunction("New", _CreatePlayDataConfig);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("Instance", get_Instance, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreatePlayDataConfig(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				PlayDataConfig obj = new PlayDataConfig();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: PlayDataConfig.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LoadConfig(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			PlayDataConfig obj = (PlayDataConfig)ToLua.CheckObject<PlayDataConfig>(L, 1);
			System.Action arg0 = (System.Action)ToLua.CheckDelegate<System.Action>(L, 2);
			obj.LoadConfig(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetDataByID(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			PlayDataConfig obj = (PlayDataConfig)ToLua.CheckObject<PlayDataConfig>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			play_data o = obj.GetDataByID(arg0);
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Instance(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, PlayDataConfig.Instance);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

