// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: cmd.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from cmd.proto</summary>
public static partial class CmdReflection {

  #region Descriptor
  /// <summary>File descriptor for cmd.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static CmdReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CgljbWQucHJvdG8ibgoJTWFpblByb3RvEhAKCHBsYXllcklEGAEgASgFEhEK",
          "CW1lc3NhZ2VJRBgCIAEoBRITCgttZXNzYWdlTmFtZRgDIAEoCRITCgttZXNz",
          "YWdlRGF0YRgEIAEoCRISCgpzZXJ2ZXJUaW1lGAUgASgBYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::MainProto), global::MainProto.Parser, new[]{ "PlayerID", "MessageID", "MessageName", "MessageData", "ServerTime" }, null, null, null)
        }));
  }
  #endregion

}
#region Messages
/// <summary>
///协议外壳
/// </summary>
public sealed partial class MainProto : pb::IMessage<MainProto> {
  private static readonly pb::MessageParser<MainProto> _parser = new pb::MessageParser<MainProto>(() => new MainProto());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<MainProto> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::CmdReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public MainProto() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public MainProto(MainProto other) : this() {
    playerID_ = other.playerID_;
    messageID_ = other.messageID_;
    messageName_ = other.messageName_;
    messageData_ = other.messageData_;
    serverTime_ = other.serverTime_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public MainProto Clone() {
    return new MainProto(this);
  }

  /// <summary>Field number for the "playerID" field.</summary>
  public const int PlayerIDFieldNumber = 1;
  private int playerID_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int PlayerID {
    get { return playerID_; }
    set {
      playerID_ = value;
    }
  }

  /// <summary>Field number for the "messageID" field.</summary>
  public const int MessageIDFieldNumber = 2;
  private int messageID_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int MessageID {
    get { return messageID_; }
    set {
      messageID_ = value;
    }
  }

  /// <summary>Field number for the "messageName" field.</summary>
  public const int MessageNameFieldNumber = 3;
  private string messageName_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string MessageName {
    get { return messageName_; }
    set {
      messageName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "messageData" field.</summary>
  public const int MessageDataFieldNumber = 4;
  private string messageData_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string MessageData {
    get { return messageData_; }
    set {
      messageData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "serverTime" field.</summary>
  public const int ServerTimeFieldNumber = 5;
  private double serverTime_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public double ServerTime {
    get { return serverTime_; }
    set {
      serverTime_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as MainProto);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(MainProto other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (PlayerID != other.PlayerID) return false;
    if (MessageID != other.MessageID) return false;
    if (MessageName != other.MessageName) return false;
    if (MessageData != other.MessageData) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(ServerTime, other.ServerTime)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (PlayerID != 0) hash ^= PlayerID.GetHashCode();
    if (MessageID != 0) hash ^= MessageID.GetHashCode();
    if (MessageName.Length != 0) hash ^= MessageName.GetHashCode();
    if (MessageData.Length != 0) hash ^= MessageData.GetHashCode();
    if (ServerTime != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(ServerTime);
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (PlayerID != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(PlayerID);
    }
    if (MessageID != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(MessageID);
    }
    if (MessageName.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(MessageName);
    }
    if (MessageData.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(MessageData);
    }
    if (ServerTime != 0D) {
      output.WriteRawTag(41);
      output.WriteDouble(ServerTime);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (PlayerID != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(PlayerID);
    }
    if (MessageID != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(MessageID);
    }
    if (MessageName.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(MessageName);
    }
    if (MessageData.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(MessageData);
    }
    if (ServerTime != 0D) {
      size += 1 + 8;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(MainProto other) {
    if (other == null) {
      return;
    }
    if (other.PlayerID != 0) {
      PlayerID = other.PlayerID;
    }
    if (other.MessageID != 0) {
      MessageID = other.MessageID;
    }
    if (other.MessageName.Length != 0) {
      MessageName = other.MessageName;
    }
    if (other.MessageData.Length != 0) {
      MessageData = other.MessageData;
    }
    if (other.ServerTime != 0D) {
      ServerTime = other.ServerTime;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          PlayerID = input.ReadInt32();
          break;
        }
        case 16: {
          MessageID = input.ReadInt32();
          break;
        }
        case 26: {
          MessageName = input.ReadString();
          break;
        }
        case 34: {
          MessageData = input.ReadString();
          break;
        }
        case 41: {
          ServerTime = input.ReadDouble();
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
