// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: cmd.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from cmd.proto</summary>
public static partial class CmdReflection {

  #region Descriptor
  /// <summary>File descriptor for cmd.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static CmdReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CgljbWQucHJvdG8idQoKcm9vdF9wcm90bxISCgpjb25uZWN0X0lEGAEgASgF",
          "EhIKCm1lc3NhZ2VfSUQYAiABKAUSFAoMbWVzc2FnZV9uYW1lGAMgASgJEhQK",
          "DG1lc3NhZ2VfZGF0YRgEIAEoDBITCgtzZXJ2ZXJfdGltZRgFIAEoASKqAQoS",
          "c3RydWN0X3BsYXllcl9pbmZvEhEKCXVzZXJfbmFtZRgBIAEoCRIRCgl1c2Vy",
          "X2ljb24YAiABKAkSDgoGZW5lcmd5GAMgASgFEgwKBGdlbXMYBCABKAUSIQoF",
          "bGV2ZWwYBSABKA4yEi5lbnVtX3BsYXllcl9sZXZlbBItCgtwcm9maWNpZW5j",
          "eRgGIAEoDjIYLmVudW1fcGxheWVyX3Byb2ZpY2llbmN5Ik8KFnJlcV9tZXNz",
          "YWdlX2xvZ2luX2dhbWUSDwoHdXNlcl9JRBgBIAEoCRIRCgl1c2VyX25hbWUY",
          "AiABKAkSEQoJdXNlcl9pY29uGAMgASgJIlAKFnJlcF9tZXNzYWdlX2xvZ2lu",
          "X2dhbWUSDAoEaXNPSxgBIAEoBRIoCgtwbGF5ZXJfaW5mbxgCIAEoCzITLnN0",
          "cnVjdF9wbGF5ZXJfaW5mbyJDChdyZXBfbWVzc2FnZV9wbGF5ZXJfaW5mbxIo",
          "CgtwbGF5ZXJfaW5mbxgBIAEoCzITLnN0cnVjdF9wbGF5ZXJfaW5mbypQChFl",
          "bnVtX3BsYXllcl9sZXZlbBIKCgZDT1BQRVIQABIKCgZTSUxWRVIQARIICgRH",
          "T0xEEAMSDAoIUExBVElOVU0QBBILCgdESUFNT05EEAUqdgoXZW51bV9wbGF5",
          "ZXJfcHJvZmljaWVuY3kSBwoDVE9FEAASCAoEQ0FMRhABEggKBEtORUUQAhIJ",
          "CgVUSElHSBADEggKBEJVVFQQBBIJCgVCRUxMWRAFEgkKBUNIRVNUEAYSCAoE",
          "TkVDSxAHEgkKBUJSQUlOEAhiBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::enum_player_level), typeof(global::enum_player_proficiency), }, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::root_proto), global::root_proto.Parser, new[]{ "ConnectID", "MessageID", "MessageName", "MessageData", "ServerTime" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::struct_player_info), global::struct_player_info.Parser, new[]{ "UserName", "UserIcon", "Energy", "Gems", "Level", "Proficiency" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::req_message_login_game), global::req_message_login_game.Parser, new[]{ "UserID", "UserName", "UserIcon" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::rep_message_login_game), global::rep_message_login_game.Parser, new[]{ "IsOK", "PlayerInfo" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::rep_message_player_info), global::rep_message_player_info.Parser, new[]{ "PlayerInfo" }, null, null, null)
        }));
  }
  #endregion

}
#region Enums
/// <summary>
///等级枚举
/// </summary>
public enum enum_player_level {
  /// <summary>
  ///青铜
  /// </summary>
  [pbr::OriginalName("COPPER")] Copper = 0,
  /// <summary>
  ///白银
  /// </summary>
  [pbr::OriginalName("SILVER")] Silver = 1,
  /// <summary>
  ///黄金
  /// </summary>
  [pbr::OriginalName("GOLD")] Gold = 3,
  /// <summary>
  ///铂金
  /// </summary>
  [pbr::OriginalName("PLATINUM")] Platinum = 4,
  /// <summary>
  ///钻石
  /// </summary>
  [pbr::OriginalName("DIAMOND")] Diamond = 5,
}

/// <summary>
///熟练度枚举
/// </summary>
public enum enum_player_proficiency {
  /// <summary>
  ///脚趾
  /// </summary>
  [pbr::OriginalName("TOE")] Toe = 0,
  /// <summary>
  ///小腿
  /// </summary>
  [pbr::OriginalName("CALF")] Calf = 1,
  /// <summary>
  ///膝盖
  /// </summary>
  [pbr::OriginalName("KNEE")] Knee = 2,
  /// <summary>
  ///大腿
  /// </summary>
  [pbr::OriginalName("THIGH")] Thigh = 3,
  /// <summary>
  ///屁股
  /// </summary>
  [pbr::OriginalName("BUTT")] Butt = 4,
  /// <summary>
  ///肚子
  /// </summary>
  [pbr::OriginalName("BELLY")] Belly = 5,
  /// <summary>
  ///胸膛
  /// </summary>
  [pbr::OriginalName("CHEST")] Chest = 6,
  /// <summary>
  ///脖子
  /// </summary>
  [pbr::OriginalName("NECK")] Neck = 7,
  /// <summary>
  ///大脑	
  /// </summary>
  [pbr::OriginalName("BRAIN")] Brain = 8,
}

#endregion

#region Messages
/// <summary>
///协议外壳
/// </summary>
public sealed partial class root_proto : pb::IMessage<root_proto> {
  private static readonly pb::MessageParser<root_proto> _parser = new pb::MessageParser<root_proto>(() => new root_proto());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<root_proto> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::CmdReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public root_proto() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public root_proto(root_proto other) : this() {
    connectID_ = other.connectID_;
    messageID_ = other.messageID_;
    messageName_ = other.messageName_;
    messageData_ = other.messageData_;
    serverTime_ = other.serverTime_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public root_proto Clone() {
    return new root_proto(this);
  }

  /// <summary>Field number for the "connect_ID" field.</summary>
  public const int ConnectIDFieldNumber = 1;
  private int connectID_;
  /// <summary>
  ///客户端标识
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int ConnectID {
    get { return connectID_; }
    set {
      connectID_ = value;
    }
  }

  /// <summary>Field number for the "message_ID" field.</summary>
  public const int MessageIDFieldNumber = 2;
  private int messageID_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int MessageID {
    get { return messageID_; }
    set {
      messageID_ = value;
    }
  }

  /// <summary>Field number for the "message_name" field.</summary>
  public const int MessageNameFieldNumber = 3;
  private string messageName_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string MessageName {
    get { return messageName_; }
    set {
      messageName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "message_data" field.</summary>
  public const int MessageDataFieldNumber = 4;
  private pb::ByteString messageData_ = pb::ByteString.Empty;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pb::ByteString MessageData {
    get { return messageData_; }
    set {
      messageData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "server_time" field.</summary>
  public const int ServerTimeFieldNumber = 5;
  private double serverTime_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public double ServerTime {
    get { return serverTime_; }
    set {
      serverTime_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as root_proto);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(root_proto other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (ConnectID != other.ConnectID) return false;
    if (MessageID != other.MessageID) return false;
    if (MessageName != other.MessageName) return false;
    if (MessageData != other.MessageData) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(ServerTime, other.ServerTime)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (ConnectID != 0) hash ^= ConnectID.GetHashCode();
    if (MessageID != 0) hash ^= MessageID.GetHashCode();
    if (MessageName.Length != 0) hash ^= MessageName.GetHashCode();
    if (MessageData.Length != 0) hash ^= MessageData.GetHashCode();
    if (ServerTime != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(ServerTime);
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (ConnectID != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(ConnectID);
    }
    if (MessageID != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(MessageID);
    }
    if (MessageName.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(MessageName);
    }
    if (MessageData.Length != 0) {
      output.WriteRawTag(34);
      output.WriteBytes(MessageData);
    }
    if (ServerTime != 0D) {
      output.WriteRawTag(41);
      output.WriteDouble(ServerTime);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (ConnectID != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(ConnectID);
    }
    if (MessageID != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(MessageID);
    }
    if (MessageName.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(MessageName);
    }
    if (MessageData.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(MessageData);
    }
    if (ServerTime != 0D) {
      size += 1 + 8;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(root_proto other) {
    if (other == null) {
      return;
    }
    if (other.ConnectID != 0) {
      ConnectID = other.ConnectID;
    }
    if (other.MessageID != 0) {
      MessageID = other.MessageID;
    }
    if (other.MessageName.Length != 0) {
      MessageName = other.MessageName;
    }
    if (other.MessageData.Length != 0) {
      MessageData = other.MessageData;
    }
    if (other.ServerTime != 0D) {
      ServerTime = other.ServerTime;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          ConnectID = input.ReadInt32();
          break;
        }
        case 16: {
          MessageID = input.ReadInt32();
          break;
        }
        case 26: {
          MessageName = input.ReadString();
          break;
        }
        case 34: {
          MessageData = input.ReadBytes();
          break;
        }
        case 41: {
          ServerTime = input.ReadDouble();
          break;
        }
      }
    }
  }

}

public sealed partial class struct_player_info : pb::IMessage<struct_player_info> {
  private static readonly pb::MessageParser<struct_player_info> _parser = new pb::MessageParser<struct_player_info>(() => new struct_player_info());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<struct_player_info> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::CmdReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public struct_player_info() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public struct_player_info(struct_player_info other) : this() {
    userName_ = other.userName_;
    userIcon_ = other.userIcon_;
    energy_ = other.energy_;
    gems_ = other.gems_;
    level_ = other.level_;
    proficiency_ = other.proficiency_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public struct_player_info Clone() {
    return new struct_player_info(this);
  }

  /// <summary>Field number for the "user_name" field.</summary>
  public const int UserNameFieldNumber = 1;
  private string userName_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string UserName {
    get { return userName_; }
    set {
      userName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "user_icon" field.</summary>
  public const int UserIconFieldNumber = 2;
  private string userIcon_ = "";
  /// <summary>
  ///暂时没用
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string UserIcon {
    get { return userIcon_; }
    set {
      userIcon_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "energy" field.</summary>
  public const int EnergyFieldNumber = 3;
  private int energy_;
  /// <summary>
  ///体力
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int Energy {
    get { return energy_; }
    set {
      energy_ = value;
    }
  }

  /// <summary>Field number for the "gems" field.</summary>
  public const int GemsFieldNumber = 4;
  private int gems_;
  /// <summary>
  ///钻石
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int Gems {
    get { return gems_; }
    set {
      gems_ = value;
    }
  }

  /// <summary>Field number for the "level" field.</summary>
  public const int LevelFieldNumber = 5;
  private global::enum_player_level level_ = 0;
  /// <summary>
  ///等级（新手）	
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::enum_player_level Level {
    get { return level_; }
    set {
      level_ = value;
    }
  }

  /// <summary>Field number for the "proficiency" field.</summary>
  public const int ProficiencyFieldNumber = 6;
  private global::enum_player_proficiency proficiency_ = 0;
  /// <summary>
  ///熟练度（脚趾）
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::enum_player_proficiency Proficiency {
    get { return proficiency_; }
    set {
      proficiency_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as struct_player_info);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(struct_player_info other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (UserName != other.UserName) return false;
    if (UserIcon != other.UserIcon) return false;
    if (Energy != other.Energy) return false;
    if (Gems != other.Gems) return false;
    if (Level != other.Level) return false;
    if (Proficiency != other.Proficiency) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (UserName.Length != 0) hash ^= UserName.GetHashCode();
    if (UserIcon.Length != 0) hash ^= UserIcon.GetHashCode();
    if (Energy != 0) hash ^= Energy.GetHashCode();
    if (Gems != 0) hash ^= Gems.GetHashCode();
    if (Level != 0) hash ^= Level.GetHashCode();
    if (Proficiency != 0) hash ^= Proficiency.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (UserName.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(UserName);
    }
    if (UserIcon.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(UserIcon);
    }
    if (Energy != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(Energy);
    }
    if (Gems != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(Gems);
    }
    if (Level != 0) {
      output.WriteRawTag(40);
      output.WriteEnum((int) Level);
    }
    if (Proficiency != 0) {
      output.WriteRawTag(48);
      output.WriteEnum((int) Proficiency);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (UserName.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(UserName);
    }
    if (UserIcon.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(UserIcon);
    }
    if (Energy != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Energy);
    }
    if (Gems != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Gems);
    }
    if (Level != 0) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Level);
    }
    if (Proficiency != 0) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Proficiency);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(struct_player_info other) {
    if (other == null) {
      return;
    }
    if (other.UserName.Length != 0) {
      UserName = other.UserName;
    }
    if (other.UserIcon.Length != 0) {
      UserIcon = other.UserIcon;
    }
    if (other.Energy != 0) {
      Energy = other.Energy;
    }
    if (other.Gems != 0) {
      Gems = other.Gems;
    }
    if (other.Level != 0) {
      Level = other.Level;
    }
    if (other.Proficiency != 0) {
      Proficiency = other.Proficiency;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          UserName = input.ReadString();
          break;
        }
        case 18: {
          UserIcon = input.ReadString();
          break;
        }
        case 24: {
          Energy = input.ReadInt32();
          break;
        }
        case 32: {
          Gems = input.ReadInt32();
          break;
        }
        case 40: {
          level_ = (global::enum_player_level) input.ReadEnum();
          break;
        }
        case 48: {
          proficiency_ = (global::enum_player_proficiency) input.ReadEnum();
          break;
        }
      }
    }
  }

}

/// <summary>
///登陆协议
/// </summary>
public sealed partial class req_message_login_game : pb::IMessage<req_message_login_game> {
  private static readonly pb::MessageParser<req_message_login_game> _parser = new pb::MessageParser<req_message_login_game>(() => new req_message_login_game());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<req_message_login_game> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::CmdReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public req_message_login_game() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public req_message_login_game(req_message_login_game other) : this() {
    userID_ = other.userID_;
    userName_ = other.userName_;
    userIcon_ = other.userIcon_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public req_message_login_game Clone() {
    return new req_message_login_game(this);
  }

  /// <summary>Field number for the "user_ID" field.</summary>
  public const int UserIDFieldNumber = 1;
  private string userID_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string UserID {
    get { return userID_; }
    set {
      userID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "user_name" field.</summary>
  public const int UserNameFieldNumber = 2;
  private string userName_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string UserName {
    get { return userName_; }
    set {
      userName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "user_icon" field.</summary>
  public const int UserIconFieldNumber = 3;
  private string userIcon_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string UserIcon {
    get { return userIcon_; }
    set {
      userIcon_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as req_message_login_game);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(req_message_login_game other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (UserID != other.UserID) return false;
    if (UserName != other.UserName) return false;
    if (UserIcon != other.UserIcon) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (UserID.Length != 0) hash ^= UserID.GetHashCode();
    if (UserName.Length != 0) hash ^= UserName.GetHashCode();
    if (UserIcon.Length != 0) hash ^= UserIcon.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (UserID.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(UserID);
    }
    if (UserName.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(UserName);
    }
    if (UserIcon.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(UserIcon);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (UserID.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(UserID);
    }
    if (UserName.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(UserName);
    }
    if (UserIcon.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(UserIcon);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(req_message_login_game other) {
    if (other == null) {
      return;
    }
    if (other.UserID.Length != 0) {
      UserID = other.UserID;
    }
    if (other.UserName.Length != 0) {
      UserName = other.UserName;
    }
    if (other.UserIcon.Length != 0) {
      UserIcon = other.UserIcon;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          UserID = input.ReadString();
          break;
        }
        case 18: {
          UserName = input.ReadString();
          break;
        }
        case 26: {
          UserIcon = input.ReadString();
          break;
        }
      }
    }
  }

}

public sealed partial class rep_message_login_game : pb::IMessage<rep_message_login_game> {
  private static readonly pb::MessageParser<rep_message_login_game> _parser = new pb::MessageParser<rep_message_login_game>(() => new rep_message_login_game());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<rep_message_login_game> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::CmdReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public rep_message_login_game() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public rep_message_login_game(rep_message_login_game other) : this() {
    isOK_ = other.isOK_;
    playerInfo_ = other.playerInfo_ != null ? other.playerInfo_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public rep_message_login_game Clone() {
    return new rep_message_login_game(this);
  }

  /// <summary>Field number for the "isOK" field.</summary>
  public const int IsOKFieldNumber = 1;
  private int isOK_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int IsOK {
    get { return isOK_; }
    set {
      isOK_ = value;
    }
  }

  /// <summary>Field number for the "player_info" field.</summary>
  public const int PlayerInfoFieldNumber = 2;
  private global::struct_player_info playerInfo_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::struct_player_info PlayerInfo {
    get { return playerInfo_; }
    set {
      playerInfo_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as rep_message_login_game);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(rep_message_login_game other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (IsOK != other.IsOK) return false;
    if (!object.Equals(PlayerInfo, other.PlayerInfo)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (IsOK != 0) hash ^= IsOK.GetHashCode();
    if (playerInfo_ != null) hash ^= PlayerInfo.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (IsOK != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(IsOK);
    }
    if (playerInfo_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(PlayerInfo);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (IsOK != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(IsOK);
    }
    if (playerInfo_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(PlayerInfo);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(rep_message_login_game other) {
    if (other == null) {
      return;
    }
    if (other.IsOK != 0) {
      IsOK = other.IsOK;
    }
    if (other.playerInfo_ != null) {
      if (playerInfo_ == null) {
        playerInfo_ = new global::struct_player_info();
      }
      PlayerInfo.MergeFrom(other.PlayerInfo);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          IsOK = input.ReadInt32();
          break;
        }
        case 18: {
          if (playerInfo_ == null) {
            playerInfo_ = new global::struct_player_info();
          }
          input.ReadMessage(playerInfo_);
          break;
        }
      }
    }
  }

}

/// <summary>
///同步玩家数据
/// </summary>
public sealed partial class rep_message_player_info : pb::IMessage<rep_message_player_info> {
  private static readonly pb::MessageParser<rep_message_player_info> _parser = new pb::MessageParser<rep_message_player_info>(() => new rep_message_player_info());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<rep_message_player_info> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::CmdReflection.Descriptor.MessageTypes[4]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public rep_message_player_info() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public rep_message_player_info(rep_message_player_info other) : this() {
    playerInfo_ = other.playerInfo_ != null ? other.playerInfo_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public rep_message_player_info Clone() {
    return new rep_message_player_info(this);
  }

  /// <summary>Field number for the "player_info" field.</summary>
  public const int PlayerInfoFieldNumber = 1;
  private global::struct_player_info playerInfo_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::struct_player_info PlayerInfo {
    get { return playerInfo_; }
    set {
      playerInfo_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as rep_message_player_info);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(rep_message_player_info other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(PlayerInfo, other.PlayerInfo)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (playerInfo_ != null) hash ^= PlayerInfo.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (playerInfo_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(PlayerInfo);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (playerInfo_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(PlayerInfo);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(rep_message_player_info other) {
    if (other == null) {
      return;
    }
    if (other.playerInfo_ != null) {
      if (playerInfo_ == null) {
        playerInfo_ = new global::struct_player_info();
      }
      PlayerInfo.MergeFrom(other.PlayerInfo);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (playerInfo_ == null) {
            playerInfo_ = new global::struct_player_info();
          }
          input.ReadMessage(playerInfo_);
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
